kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-zf
rules:
  - apiGroups: [""]
    resources: ["namespaces","pods","deployments"]
    verbs: ["get", "watch", "list", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-zf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin-zf
subjects:
- kind: Group
  name: "admin"
  apiGroup: rbac.authorization.k8s.ioapiVersion: rbac.authorization.k8s.io/v1
  