apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Mo2menAdel/kubernetes-common-apps.git'
    path: applications-deployment/mongodb
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mongodb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true